language: node_js
env:
  global:
    - GH_REF: github.com/w3c/coga.git
    
git:
  depth: 3
  
branches:
  only:
    master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/coga.git
  - cd coga
  - cp -R ../../w3c/coga/user-research .
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/coga/master/user-research/index.html -o user-research/index.html -f
  - cp -R ../../w3c/coga/issue-papers .
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/coga/master/issue-papers/index.html -o issue-papers/index.html -f
  - cp -R ../../w3c/coga/gap-analysis .
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/coga/master/gap-analysis/index.html -o gap-analysis/index.html -f
#  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/coga/master/gap-analysis/semantics.html -o gap-analysis/semantics.html -f
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/coga/master/extension/index.html -o extension/index.html -f
  - cp -R ../../w3c/coga/techniques .
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/coga/master/techniques/index.html -o techniques/index.html -f
  - cp -R ../../w3c/coga/persona .
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/coga/master/persona/index.html -o persona/index.html -f
  - cp -R ../../w3c/coga/content-usable .
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/coga/master/content-usable/index.html -o content-usable/index.html -f


after_success:
  - git add -A .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages > /dev/null 2>&1
